In [16]:
import torch
import torch.nn.functional as F
e1 = torch.randn([3,3])
e2 = torch.randn([3,3])
# print(e1)
# print(e2)
m1 = e1
m2 = e2
# m1 = torch.tanh(e1)
# m2 = torch.tanh(e2)
# mid = torch.mm(m1, m2.t()) - torch.mm(m2, m1.t())
# print(mid)
# mid2 = torch.mm(m1, m2.t()).sub(torch.mm(m2, m1.t()))
# print(mid2)

mid3 = F.relu(torch.tanh(torch.mm(m1, m2.t()) - torch.mm(m2, m1.t())))
print(mid3)
adp = F.softmax(mid3, dim=1)
print(adp)
adp = F.softmax(mid3, dim=0)
print(adp)

tensor([[0.0000, 0.9999, 0.8874],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.9906, 0.0000]])
tensor([[0.1627, 0.4422, 0.3951],
        [0.3333, 0.3333, 0.3333],
        [0.2131, 0.5738, 0.2131]])
tensor([[0.3333, 0.4240, 0.5484],
        [0.3333, 0.1560, 0.2258],
        [0.3333, 0.4201, 0.2258]])


In [1]:
import pandas as pd
df = pd.read_csv('data/water/water2020.csv',
                 usecols=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(df.columns)

Index(['监测时间', '站点名称', 'pH值', '总氮', '总磷', '氨氮', '水温', '浑浊度', '溶解氧', '电导率',
       '高锰酸盐指数'],
      dtype='object')
