# automl
~~使用autogluon训练数据~~

In [1]:
import pandas
df = pandas.read_hdf('data/water/shangban/singleFac/merge0.h5')
df.head(5)




天宝大水港排涝站0  中排渠涝站（天宝）0  甘棠溪慧民花园监测点0  康山溪金峰花园监测点0  芗城水利局站0  \
time                                                                            
2020-01-01 00:00:00      8.255       6.285        7.092        6.453    8.165   
2020-01-01 04:00:00      8.132       6.300        7.090        6.448    8.200   
2020-01-01 08:00:00      8.183       6.368        7.115        6.465    8.205   
2020-01-01 12:00:00      8.348       6.395        7.113        6.470    8.222   
2020-01-01 16:00:00      8.418       6.300        7.065        6.498    8.162   

                     中山桥水闸站0  北京路水闸站0  九湖监测点0  桂林排涝站0    上坂0  
time                                                          
2020-01-01 00:00:00    6.641    6.240   6.790   8.288  6.859  
2020-01-01 04:00:00    6.640    6.258   6.805   8.375  6.805  
2020-01-01 08:00:00    6.640    6.180   6.785   8.327  6.758  
2020-01-01 12:00:00    6.639    6.185   6.850   8.242  6.766  
2020-01-01 16:00:00    6.638    6.098   6.915   8.222  6.754

In [22]:
import numpy as np

# We define two sequences x, y as numpy array
# where y is actually a sub-sequence from x
x = np.array([2, 0, 1, 1, 2, 4, 2, 1, 2, 0]).reshape(10, 1)
y = np.array([1, 1, 2, 4, 2, 1, 2, 0, 3, 4]).reshape(10, 1)
print(x.shape)
from dtw import dtw

manhattan_distance = lambda x, y: np.abs(x - y)

d, _, _, _ = dtw(x, y, dist=manhattan_distance)

print(d)

(10, 1)
9.0


In [41]:
from dtw import dtw
manhattan_distance = lambda x, y: np.abs(x - y)

x = np.ones([64,2,10,24])
# yy = np.ones([64,2,10,24])
print(x.shape)

x = x[:,0:-1,:,:]
print(x.shape)

dist = np.zeros([x.shape[0],x.shape[1],x.shape[2],x.shape[2]])
for a in range(x.shape[0]):
    for b in range(x.shape[1]):
        for c in range(x.shape[2]):
            for d in range(x.shape[2]):
                seq_x = x[a,b,c,:]
                seq_y = x[a,b,d,:]
                r = dtw(seq_x, seq_y, dist=manhattan_distance)
                dist[a,b,c,d] = r[0]
print(dist)

print('done')

(64, 2, 10, 24)
(64, 1, 10, 24)
[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 ...


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0

In [4]:
import torch

x = torch.ones([2,3,4])
print(x.shape)

y = x[0] 
print(y.shape)




torch.Size([2, 3, 4])
torch.Size([3, 4])
