In [13]:
import numpy as np

num_node = 5
x = [1 for i in range(num_node)]
a = np.diag(x)
a[:,num_node - 1] = 1
print(a)

w = np.random.rand(5, 5)
print(w)

print(a * w)




[[1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]
[[0.59524725 0.56080857 0.91790485 0.91266134 0.48548729]
 [0.17441106 0.03483753 0.06774446 0.95673277 0.89551167]
 [0.79553671 0.98142293 0.97029952 0.8980935  0.06958471]
 [0.87282973 0.55332104 0.92246897 0.29615934 0.54084285]
 [0.78009545 0.41381551 0.88419041 0.72125579 0.45922045]]
[[0.59524725 0.         0.         0.         0.48548729]
 [0.         0.03483753 0.         0.         0.89551167]
 [0.         0.         0.97029952 0.         0.06958471]
 [0.         0.         0.         0.29615934 0.54084285]
 [0.         0.         0.         0.         0.45922045]]


In [ ]:
ids = [ '天宝大水港排涝站','中排渠涝站（天宝）',
             '程溪下庄工业区水质监测点', '甘棠溪慧民花园监测点',
        '康山溪金峰花园监测点', '芗城水利局站','中山桥水闸站', '北京路水闸站','九湖监测点','桂林排涝站','上坂']


In [29]:
import pandas as pd

adj_df = pd.read_csv('data/water/adjs/adj_shangban.csv')
adj_df = adj_df.fillna(0)
adj_df = adj_df.iloc[:,1:]
adj = adj_df.values
print(adj)


w = np.random.randn(11,11)
print(adj * w)


[[1. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[-1.02440977 -1.16621931 -0.         -0.          0.         -0.6794237
  -1.21417108 -0.26566141  0.          0.39579619  1.40344522]
 [ 0.         -0.37140196 -0.          0.          0.          0.15052917
   0.4872125   0.38191412 -0.         -1.31529965  0.73263645]
 [-0.          0.          0.61496594  0.         -0.          0.64992469
  -0.33571248  0.43009298  0.         -0.80089819  1.69933338]
 [-0.         -0.          0.         -0.39097492  0.16414821 -0.71959347
  -0.16683069  1.06849253 -0.          0.06622919  0.92721503]
 [-0.         -0.          0.         -0.         -0.931

In [36]:
aa = np.random.randn(3,3)
aa = np.triu(aa)
print(aa)
bb = np.random.randn(3,3)
print(bb)

import torch
taa = torch.from_numpy(aa)
tbb = torch.from_numpy(bb)
print(torch.mm(tbb,taa))

print('---')
print(aa * bb)
print(bb * aa)


[[-1.52133186  0.13337864  0.0150728 ]
 [ 0.          0.30392785 -0.07009754]
 [ 0.          0.          2.21580656]]
[[ 0.18263928 -0.73545273  2.17612999]
 [-1.89190736 -0.54422888  1.15181693]
 [ 0.72618285  1.47423761  0.4574909 ]]
tensor([[-0.2779, -0.1992,  4.8762],
        [ 2.8782, -0.4177,  2.5618],
        [-1.1048,  0.5449,  0.9213]], dtype=torch.float64)
---
[[-0.27785495 -0.09809368  0.03280038]
 [-0.         -0.16540632 -0.08073954]
 [ 0.          0.          1.01371134]]
[[-0.27785495 -0.09809368  0.03280038]
 [-0.         -0.16540632 -0.08073954]
 [ 0.          0.          1.01371134]]
